name: fl_paging
description: A new Flutter package support paginating for Listview, Gridview and NestedScrollView
version: 1.0.21
homepage: https://github.com/dangngocduc/flutter_paging
repository: https://github.com/dangngocduc/flutter_paging
issue_tracker: https://github.com/dangngocduc/flutter_paging/issues
documentation: https://github.com/dangngocduc/flutter_paging

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.12.0
  tuple: ^1.0.3
  async: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  freezed: ^0.11.6
flutter:
